update structure
apawlik96/to-do-list pull request #2
Opened 2024-08-14 12:24 UTC by apawlik96

2024-08-14 15:10 UTC, przemek-ycd requested changes

2024-08-14 15:10 UTC, przemek-ycd commented on src/components/Task/Task.jsx
> +  const [markTask, setMarkTask] = useState(false);
```suggestion
  const [isTaskMarked, setIsTaskMarked] = useState(false);
```

You'd wanna use verbs only to name functions, not variables

2024-08-14 15:10 UTC, przemek-ycd commented on src/components/Task/Task.jsx
> +    setMarkTask((prevMarkTask) => !prevMarkTask);
That's very good. Do you have an understanding, why you couldn't have just done:

```
setMarkTask(!markTask)
```

?

2024-08-14 15:10 UTC, przemek-ycd commented on src/components/Task/Task.jsx
> +    <Div>
Can you rename all these styled components following the convention: `Styled...`
so this would be sth like `StyledWrapper`

2024-08-14 15:10 UTC, przemek-ycd commented on src/components/Task/Task.jsx
> +      {!markTask ? <P>{text}</P> : <PMark>{text}</PMark>}
1. As often as possible you'd wanna not negate statements in conditions. More natural here would be "if task is marked..."
2. `P` and `PMark` are almost identical styles. Only color and `line-through` are applied here when the task is marked.

What you could do, is have only one component, that is parametrized. So what I'd wanna see here is sth like:
```
<P isMarked={isMarked}>{text}</P>
```

Here's a bit more on how to pass properties to Styled component: https://styled-components.com/docs/basics#passed-props

Once you learn this, you'll discover the beauty of Styled Components, b/c you'll notice, you can change styles on the fly with use of JavaScript. Hence the name of the approach: CSS-in-JS

2024-08-14 15:10 UTC, przemek-ycd commented on src/containers/ToDoList/ToDoList.jsx
> +        ))}
Very nice!

2024-08-15 08:24 UTC, apawlik96 commented on src/components/Task/Task.jsx
> +    setMarkTask((prevMarkTask) => !prevMarkTask);
because this solution provides access to the latest state

2024-08-17 09:42 UTC, przemek-ycd approved these changes

2024-08-17 13:08 UTC, merged